# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use
# For example: application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================
spring.config.import: optional:configserver:http://localhost:8888

spring:
  cloud:
    config:
      uri: http://localhost:8888

logging:
  level:
    root: info
    com.dct.discovery: info
  charset:
    console: UTF-8
    file: UTF-8
  file:
    path: /opt/logs/discovery-server

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  server:
    waitTimeInMsWhenSyncEmpty: 180000 # 3 minutes
    eviction-interval-timer-in-ms: 300000 # 5 minutes
    enableSelfPreservation: true
